# Generated by Django 2.1.15 on 2020-04-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailnhsukfrontendsettings', '0006_auto_20200415_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='organisation_split_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
