# Generated by Django 2.1.15 on 2020-04-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailnhsukfrontendsettings', '0007_headersettings_organisation_split_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headersettings',
            name='organisational',
        ),
    ]
